version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: airlines
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: testtest
      POSTGRES_DB: airlines